language: node_js
node_js: 14

jobs:
    include:
        - stage: build
          script: npm install

        - stage: test
          script:
              - npm install --global prettier
              - prettier --check .
